import asyncio
import os
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Dict, Optional

from aiogram import Bot, Dispatcher, F
from aiogram.enums import ParseMode
from aiogram.filters import Command
from aiogram.fsm.context import FSMContext
from aiogram.fsm.state import State, StatesGroup
from aiogram.fsm.storage.memory import MemoryStorage
from aiogram.types import FSInputFile, Message
from dotenv import load_dotenv
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas


load_dotenv()

BOT_TOKEN = os.getenv("BOT_TOKEN", "")
DEFAULT_CHANNEL_ID = os.getenv("DEFAULT_CHANNEL_ID", "")
ADMIN_IDS = {
    int(x.strip())
    for x in os.getenv("ADMIN_IDS", "").split(",")
    if x.strip().isdigit()
}

TICKETS_DIR = Path("tickets")
TICKETS_DIR.mkdir(parents=True, exist_ok=True)


@dataclass
class AutopostJob:
    interval_minutes: int
    channel_id: str
    text: str
    task: asyncio.Task


autopost_jobs: Dict[int, AutopostJob] = {}


class AutopostForm(StatesGroup):
    interval = State()
    channel = State()
    text = State()


class TicketForm(StatesGroup):
    full_name = State()
    birth_date = State()
    from_city = State()
    to_city = State()
    flight_number = State()
    flight_date = State()
    departure_time = State()
    seat = State()
    booking_number = State()
    ticket_number = State()
    price = State()


def is_admin(user_id: int) -> bool:
    return user_id in ADMIN_IDS


async def run_autopost(bot: Bot, owner_id: int) -> None:
    while True:
        job = autopost_jobs.get(owner_id)
        if not job:
            return

        try:
            await bot.send_message(chat_id=job.channel_id, text=job.text)
        except Exception as e:
            print(f"[autopost error] owner={owner_id}: {e}")

        await asyncio.sleep(job.interval_minutes * 60)


def build_ticket_pdf(data: dict, output_path: Path) -> None:
    c = canvas.Canvas(str(output_path), pagesize=A4)
    width, height = A4

    c.setFont("Helvetica-Bold", 18)
    c.drawString(20 * mm, height - 20 * mm, "ZARAFSHAN TRAVEL")

    c.setFont("Helvetica", 11)
    c.drawString(20 * mm, height - 28 * mm, "Electronic Air Ticket")
    c.drawString(20 * mm, height - 36 * mm, f"Issued: {datetime.now().strftime('%Y-%m-%d %H:%M')}")

    y = height - 50 * mm
    line_gap = 9 * mm

    fields = [
        ("Passenger (FIO)", data["full_name"]),
        ("Birth date", data["birth_date"]),
        ("Route", f"{data['from_city']} -> {data['to_city']}"),
        ("Flight number", data["flight_number"]),
        ("Flight date", data["flight_date"]),
        ("Departure time", data["departure_time"]),
        ("Seat", data["seat"]),
        ("Booking number (PNR)", data["booking_number"]),
        ("Ticket number", data["ticket_number"]),
        ("Price", data["price"]),
    ]

    for label, value in fields:
        c.setFont("Helvetica-Bold", 11)
        c.drawString(20 * mm, y, f"{label}:")
        c.setFont("Helvetica", 11)
        c.drawString(70 * mm, y, value)
        y -= line_gap

    c.setFont("Helvetica-Oblique", 9)
    c.drawString(20 * mm, 20 * mm, "This document is generated by Zarafshan Travel Telegram Bot")

    c.showPage()
    c.save()


async def cmd_start(message: Message):
    if not is_admin(message.from_user.id):
        await message.answer("У вас нет доступа к этому боту.")
        return

    await message.answer(
        "Добро пожаловать в Zarafshan Travel Bot!\n"
        "Команды:\n"
        "/autopost - настроить автопостинг\n"
        "/stop_autopost - остановить автопостинг\n"
        "/ticket - создать PDF билет\n"
        "/help - помощь"
    )


async def cmd_help(message: Message):
    await cmd_start(message)


async def cmd_autopost(message: Message, state: FSMContext):
    if not is_admin(message.from_user.id):
        await message.answer("У вас нет доступа к этой команде.")
        return

    await state.set_state(AutopostForm.interval)
    await message.answer("Введите интервал автопостинга в минутах (например: 60):")


async def autopost_interval(message: Message, state: FSMContext):
    if not message.text.isdigit() or int(message.text) <= 0:
        await message.answer("Нужно положительное число. Пример: 30")
        return

    await state.update_data(interval=int(message.text))
    await state.set_state(AutopostForm.channel)
    default_info = DEFAULT_CHANNEL_ID if DEFAULT_CHANNEL_ID else "не задан"
    await message.answer(
        f"Введите channel_id/username канала (например @my_channel или -100... )\n"
        f"Если хотите использовать default ({default_info}), отправьте: -"
    )


async def autopost_channel(message: Message, state: FSMContext):
    channel = message.text.strip()
    if channel == "-":
        if not DEFAULT_CHANNEL_ID:
            await message.answer("DEFAULT_CHANNEL_ID не задан. Введите канал вручную.")
            return
        channel = DEFAULT_CHANNEL_ID

    await state.update_data(channel=channel)
    await state.set_state(AutopostForm.text)
    await message.answer("Отправьте текст поста для автопубликации:")


async def autopost_text(message: Message, state: FSMContext, bot: Bot):
    data = await state.get_data()
    owner_id = message.from_user.id

    old_job = autopost_jobs.get(owner_id)
    if old_job:
        old_job.task.cancel()

    task = asyncio.create_task(run_autopost(bot, owner_id))
    autopost_jobs[owner_id] = AutopostJob(
        interval_minutes=data["interval"],
        channel_id=data["channel"],
        text=message.text,
        task=task,
    )

    await state.clear()
    await message.answer(
        "Автопостинг запущен:\n"
        f"• Интервал: {data['interval']} мин\n"
        f"• Канал: {data['channel']}"
    )


async def cmd_stop_autopost(message: Message):
    if not is_admin(message.from_user.id):
        await message.answer("У вас нет доступа к этой команде.")
        return

    job = autopost_jobs.pop(message.from_user.id, None)
    if not job:
        await message.answer("У вас нет активного автопостинга.")
        return

    job.task.cancel()
    await message.answer("Автопостинг остановлен.")


async def cmd_ticket(message: Message, state: FSMContext):
    if not is_admin(message.from_user.id):
        await message.answer("У вас нет доступа к этой команде.")
        return

    await state.set_state(TicketForm.full_name)
    await message.answer("Введите ФИО пассажира:")


async def ticket_flow(message: Message, state: FSMContext):
    current_state = await state.get_state()

    order = [
        (TicketForm.full_name.state, "full_name", "Введите дату рождения (YYYY-MM-DD):"),
        (TicketForm.birth_date.state, "birth_date", "Введите город отправления:"),
        (TicketForm.from_city.state, "from_city", "Введите город прибытия:"),
        (TicketForm.to_city.state, "to_city", "Введите номер рейса:"),
        (TicketForm.flight_number.state, "flight_number", "Введите дату рейса (YYYY-MM-DD):"),
        (TicketForm.flight_date.state, "flight_date", "Введите время вылета (HH:MM):"),
        (TicketForm.departure_time.state, "departure_time", "Введите место (seat), например 12A:"),
        (TicketForm.seat.state, "seat", "Введите номер брони (PNR):"),
        (TicketForm.booking_number.state, "booking_number", "Введите номер билета:"),
        (TicketForm.ticket_number.state, "ticket_number", "Введите стоимость (например 250 USD):"),
        (TicketForm.price.state, "price", "DONE"),
    ]

    for i, (state_name, key, next_prompt) in enumerate(order):
        if current_state == state_name:
            await state.update_data(**{key: message.text.strip()})

            if next_prompt == "DONE":
                data = await state.get_data()
                filename = (
                    f"ticket_{data['ticket_number'].replace(' ', '_')}_"
                    f"{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
                )
                output_path = TICKETS_DIR / filename
                build_ticket_pdf(data, output_path)

                await message.answer("PDF-билет готов. Отправляю файл...")
                await message.answer_document(document=FSInputFile(output_path))
                await state.clear()
                return

            next_state = order[i + 1][0]
            await state.set_state(next_state)
            await message.answer(next_prompt)
            return


async def main():
    if not BOT_TOKEN:
        raise RuntimeError("BOT_TOKEN is empty. Set it in .env")

    bot = Bot(token=BOT_TOKEN, parse_mode=ParseMode.HTML)
    dp = Dispatcher(storage=MemoryStorage())

    dp.message.register(cmd_start, Command("start"))
    dp.message.register(cmd_help, Command("help"))

    dp.message.register(cmd_autopost, Command("autopost"))
    dp.message.register(autopost_interval, AutopostForm.interval, F.text)
    dp.message.register(autopost_channel, AutopostForm.channel, F.text)
    dp.message.register(autopost_text, AutopostForm.text, F.text)
    dp.message.register(cmd_stop_autopost, Command("stop_autopost"))

    dp.message.register(cmd_ticket, Command("ticket"))
    dp.message.register(ticket_flow, TicketForm.full_name, F.text)
    dp.message.register(ticket_flow, TicketForm.birth_date, F.text)
    dp.message.register(ticket_flow, TicketForm.from_city, F.text)
    dp.message.register(ticket_flow, TicketForm.to_city, F.text)
    dp.message.register(ticket_flow, TicketForm.flight_number, F.text)
    dp.message.register(ticket_flow, TicketForm.flight_date, F.text)
    dp.message.register(ticket_flow, TicketForm.departure_time, F.text)
    dp.message.register(ticket_flow, TicketForm.seat, F.text)
    dp.message.register(ticket_flow, TicketForm.booking_number, F.text)
    dp.message.register(ticket_flow, TicketForm.ticket_number, F.text)
    dp.message.register(ticket_flow, TicketForm.price, F.text)

    print("Bot started...")
    await dp.start_polling(bot)


if __name__ == "__main__":
    asyncio.run(main())
